version: '3'
 
services:
    apache_1:
        container_name: microservice-one
        build: ./microservice-one
        ports: 
          - 6060:80
    apache_2:
        container_name: microservice-two
        build: ./microservice-two
        ports:
          - 7070:80
        deploy:
          resources:
            limits:
              cpus: '1'
              memory: 512M
            reservations:
              cpus: '0.5'
              memory: 256M

    haproxy_img:
        container_name: haproxy
        build: ./haproxy
        ports:
          - 80:80
